### ISSUE TITLE
Double yada and it is not clickable

### ISSUE THREAD

**Issue by folmerkrikken** [BSd3v/dash-yada#30]
Hi, 
Thanks for making this great package! 
I was planning on implementing dash-yada in a Dash climate analysis platform (www.climateradar.com/tools/clim_analyzer/#tour). I also have a 'tour' there, which are basically a bunch of dbc.Popovers together with some pattern matching callbacks. But dash-yada would offcourse be a much better solution. However, when I try the simple first example in the tutorial I can not get it working.

I get a double Yada and both are not clickable. 
![Screenshot from 2024-03-18 21-59-38](https://github.com/BSd3v/dash-yada/assets/35295222/97f2bd84-8786-454c-b1a4-8105bb9a102f)
I've also tried to run the 'live demo' app but with the same results. I don't get any error messages from Dash.

When I use 'inspect' in the browser I do get the following error directly after I hover over Yada:

react-dom@16.v2_16_1m1710794740.14.0.js:82 Warning: React does not recognize the `hasDoneInitialMeasure` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasdoneinitialmeasure` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef)
    in ForwardRef (created by r)
    in r (created by ForwardRef)
    in ForwardRef (created by Fade)
    in Fade (created by Overlay)
    in Overlay (created by Overlay)
    in Overlay (created by Qd)
    in Qd (created by sp)
    in sp (created by CheckedComponent)
    in CheckedComponent (created by BaseTreeContainer)
    in ComponentErrorBoundary (created by BaseTreeContainer)
    in BaseTreeContainer (created by DashWrapper)
    in DashWrapper (created by BaseTreeContainer)
    in div (created by et)
    in et (created by CheckedComponent)
    in CheckedComponent (created by BaseTreeContainer)
    in ComponentErrorBoundary (created by BaseTreeContainer)
    in BaseTreeContainer (created by DashWrapper)
    in DashWrapper (created by BaseTreeContainer)
    in div (created by Container)
    in Container (created by ya)
    in ya (created by CheckedComponent)
    in CheckedComponent (created by BaseTreeContainer)
    in ComponentErrorBoundary (created by BaseTreeContainer)
    in BaseTreeContainer (created by DashWrapper)
    in DashWrapper (created by UnconnectedContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in div (created by GlobalErrorOverlay)
    in div (created by GlobalErrorOverlay)
    in GlobalErrorOverlay (created by DebugMenu)
    in div (created by DebugMenu)
    in DebugMenu (created by UnconnectedGlobalErrorContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in UnconnectedGlobalErrorContainer (created by Connect(UnconnectedGlobalErrorContainer))
    in Connect(UnconnectedGlobalErrorContainer) (created by UnconnectedContainer)
    in UnconnectedContainer (created by Connect(UnconnectedContainer))
    in Connect(UnconnectedContainer) (created by UnconnectedAppContainer)
    in UnconnectedAppContainer (created by Connect(UnconnectedAppContainer))
    in Connect(UnconnectedAppContainer) (created by AppProvider)
    in Provider (created by AppProvider)
    in AppProvider

I've updated dash (2.16.1), dash_bootstrap_components (1.5.0) and dash_yada (0.0.1) all to the latest versions, but nevertheless no luck. Did you come across this behavior before already? Any ideas what is going wrong?

Thanks, Folmer

**Comment by folmerkrikken** [comment]
Ouch.. already found it myself minutes after making the issue.. after updating my google chrome browser as a last test everything works as it should. So make sure you have an up to date browser if you use this package ;-)

**Comment by BSd3v** [comment]
The double yada is more than likely an issue with the css, as it switches between active and inactive images. :)
